# Generated by Django 3.0.5 on 2021-06-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('Disease', models.CharField(max_length=50)),
                ('Doctor_Name', models.CharField(max_length=50)),
                ('Doctor_Fees', models.IntegerField(default=500)),
                ('Start_dat', models.DateField(auto_now=True)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
