# Generated by Django 3.0.5 on 2021-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(default=1),
        ),
    ]
